# 基础配置
title: 我的 Wiki
description: 团队技术 Wiki
baseurl: "/just-the-docs" # 若部署到 GitHub Pages 的 repo 二级路径，需配置（如 repo 名为 my-wiki，则填 /my-wiki）
url: "https://hankin2015.github.io" # 你的 GitHub Pages 域名

# 指定主题
remote_theme: just-the-docs/just-the-docs@v0.10.1 # 使用 GitHub 上的主题（无需本地安装）

# 必须启用远程主题插件
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# 禁用自动扫描（必须！否则会覆盖 nav）
docs_dir: "_nonexistent_dir"  # 指定不存在的目录，关闭自动生成

# 手动定义完整导航（nav 字段）
nav:
  - title: "首页"
    url: /                # 对应 README.md（根路径）
  
  - title: "基础指南"      # 一级导航
    children:             # 二级导航（必须显式定义）
      - title: "环境搭建"  # 二级项1
        url: /setup/      # 对应 setup.md
      - title: "快速上手"  # 二级项2
        url: /quickstart/ # 对应 quickstart.md
  
  - title: "关于"
    url: /about/          # 对应 about.md