title: 八股文面经集锦

remote_theme: just-the-docs/just-the-docs@v0.10.1
#remote_theme: sighingnow/jekyll-gitbook
#remote_theme: 2type/gitbook

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
